"""Simulation target abstraction interfaces."""
from __future__ import annotations

from abc import ABC, abstractmethod


class SimCommandBuilder(ABC):
    """Generates target-specific commands for simulation operations."""

    @abstractmethod
    def build_gpio_systemd_install(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_sim_diag_json(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_gpio_sim_setup(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_gpio_sim_teardown(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_systemd_install(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_systemd_start(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_systemd_stop(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_sim_start(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_sim_stop(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_sim_status(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_sim_log(self) -> str: ...
    @abstractmethod
    def build_gpio_runtime_status(self, hw_definition: dict[str, list[dict[str, str]]] | None = None) -> str: ...
    @abstractmethod
    def build_panel(self, action: str, params: dict) -> str: ...


class SimProvider(ABC):
    """High-level simulation operations on a target device."""

    @abstractmethod
    def start(self, hw_definition: dict[str, list[dict[str, str]]]) -> int: ...

    @abstractmethod
    def stop(self, hw_definition: dict[str, list[dict[str, str]]]) -> int: ...

    @abstractmethod
    def status(self, hw_definition: dict[str, list[dict[str, str]]], json_output: bool = False) -> int: ...

    @abstractmethod
    def log(self) -> int: ...

    @abstractmethod
    def diag_json(self, hw_definition: dict[str, list[dict[str, str]]]) -> int: ...

    @abstractmethod
    def gpio_sim_check(self, json_output: bool = False) -> int: ...

    @abstractmethod
    def gpio_command(self, command: str, hw_definition: dict[str, list[dict[str, str]]], json_output: bool = False) -> int: ...

    @abstractmethod
    def panel(self, action: str, params: dict, json_output: bool = False) -> int: ...
